<VendorDetailsScreen>:
    orientation: 'vertical'  # Main layout orientation is vertical

    # BoxLayout to stack the Carousel and main content
    BoxLayout:
        orientation: 'vertical'
        size_hint_y: None
        height: '640dp'  # Set a fixed height or adjust as needed

        # Carousel widget
        Carousel:
            size_hint_y: 0.7
            direction: 'right'
            AsyncImage:
                source: root.image_source
                size_hint: None, None  # Disable size hint to use absolute size
                size: self.parent.width, self.parent.height * 1  # Set image size to match Carousel size
            AsyncImage:
                source: root.gallery_images[0] if root.gallery_images else 'Gallery Images'
                size_hint: None, None  # Disable size hint to use absolute size
                size: self.parent.width, self.parent.height * 1  # Set image size to match Carousel size
            AsyncImage:
                source: root.gallery_images[1] if len(root.gallery_images) > 1 else 'Gallery Images'
                size_hint: None, None  # Disable size hint to use absolute size
                size: self.parent.width, self.parent.height * 1  # Set image size to match Carousel size

        # Main content below the Carousel
        MyCard:
            size_hint: None, None
            Label:
                id: institution_name_label
                text: root.institution_name
                color: '000000'

            Label:
                id: price_label
                text: root.price
                color: '000000'

            Label:
                id: description_label
                text: root.description
                color: '000000'

            Label:
                id: location_label
                text: root.location
                color: '000000'

            Label:
                id: service_label
                text: root.service
                color: '000000'

            Label:
                id: phone_number_label
                text: root.phone_number
                color: '000000'

            Label:
                id: email_label
                text: root.email
                color: '000000'

            Label:
                id: website_label
                text: root.website
                color: '000000'

            Label:
                id: social_media_label
                text: root.social_media
                color: '000000'

